apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

  ---
# Adservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/adservice:latest
          ports:
            - containerPort: 9555
          env:
            - name: DISABLE_PROFILER
              value: "true"
            - name: DISABLE_TRACING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: microservices-demo
spec:
  selector:
    app: adservice
  ports:
    - port: 80
      targetPort: 9555
  type: ClusterIP