apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Cartservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/cartservice:latest
          ports:
            - containerPort: 7070
          env:
            - name: DISABLE_PROFILER
              value: "true"
            - name: DISABLE_TRACING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: microservices-demo
spec:
  selector:
    app: cartservice
  ports:
    - port: 80
      targetPort: 7070
  type: ClusterIP
