apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Checkoutservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/checkoutservice:latest
          ports:
            - containerPort: 5050
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:80
            - name: PAYMENT_SERVICE_ADDR
              value: paymentservice:80
            - name: EMAIL_SERVICE_ADDR
              value: emailservice:80
            - name: CART_SERVICE_ADDR
              value: cartservice:80
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:80
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:80
            - name: DISABLE_PROFILER
              value: "true"
            - name: DISABLE_TRACING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: microservices-demo
spec:
  selector:
    app: checkoutservice
  ports:
    - port: 80
      targetPort: 5050
  type: ClusterIP
