apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Emailservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/emailservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "true"
            - name: DISABLE_TRACING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: microservices-demo
spec:
  selector:
    app: emailservice
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
