apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Loadgenerator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/loadgenerator:latest
          env:
            - name: FRONTEND_ADDR
              value: frontend:80
            - name: USERS
              value: "20"
            - name: RATE
              value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: microservices-demo
spec:
  selector:
    app: loadgenerator
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
