apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo
---
# Paymentservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/paymentservice:latest
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "true"
            - name: DISABLE_TRACING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: microservices-demo
spec:
  selector:
    app: paymentservice
  ports:
    - port: 80
      targetPort: 50051
  type: ClusterIP
