apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Recommendationservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/recommendationservice:latest
          ports:
            - containerPort: 8081
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:80
            - name: DISABLE_PROFILER
              value: "true"
            - name: DISABLE_TRACING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: microservices-demo
spec:
  selector:
    app: recommendationservice
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP
