apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Shippingservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/shippingservice:latest
          ports:
            - containerPort: 50051
          env:
            - name: DISABLE_PROFILER
              value: "true"
            - name: DISABLE_TRACING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: microservices-demo
spec:
  selector:
    app: shippingservice
  ports:
    - port: 80
      targetPort: 50051
  type: ClusterIP
