apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Shoppingassistantservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
    spec:
      containers:
        - name: shoppingassistantservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/shoppingassistantservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              value: "sk-xxx" # Replace with your real key
            - name: DB_HOST
              value: shopping-assistant-db.czcmm4esc0mr.eu-central-1.rds.amazonaws.com
            - name: DB_NAME
              value: shoppingdb
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: MySecurePass123!
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
  namespace: microservices-demo
spec:
  selector:
    app: shoppingassistantservice
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
