apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo

---
# Shoppingassistantservice Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
    spec:
      containers:
        - name: shoppingassistantservice
          image: 610351333224.dkr.ecr.eu-central-1.amazonaws.com/shoppingassistantservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: shoppingassistant-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: shoppingassistant-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shoppingassistant-secrets
                  key: DB_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shoppingassistant-secrets
                  key: OPENAI_API_KEY

---
# Shoppingassistantservice Service
apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
  namespace: microservices-demo
spec:
  selector:
    app: shoppingassistantservice
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
